In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data=pd.read_csv("train.csv")

In [3]:
data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
data.shape

(20800, 5)

In [5]:
data=data.dropna()#removing null values

In [6]:
data.shape

(18285, 5)

In [7]:
X=data.drop('label',axis=1)

In [8]:
y=data['label']

In [9]:
X #independent var

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [10]:
y #dependent variable

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [11]:
message=X.copy()

In [12]:
message.reset_index(inplace=True)# resets index as null values are removed so we need to order index again

In [13]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]

In [14]:
len(message)

18285

In [15]:
voc_size=8000

In [16]:
for i in range(0,len(message)):    
    text = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    text=text.lower()
    text=text.split()
    text=[ps.stem(word) for word in text if not word in stopwords.words("english")]

    text= " ".join(text)
    corpus.append(text)

    
    
    

In [17]:
print(len(corpus))

18285


In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
from tensorflow.keras.preprocessing.text import one_hot
onehot_rep=[one_hot(words,voc_size)for words in corpus] 
onehot_rep

[[1523, 3797, 5091, 2712, 305, 3814, 5437, 5434, 6022, 6199],
 [5702, 4521, 7740, 4455, 4081, 1247, 7539],
 [2812, 1146, 1530, 2676],
 [6795, 6597, 5966, 7476, 3151, 5705],
 [7758, 4081, 7862, 4010, 7048, 70, 4081, 689, 3042, 3237],
 [1258,
  3170,
  7099,
  5151,
  1010,
  5789,
  6629,
  5360,
  7341,
  7148,
  5877,
  4575,
  654,
  7723,
  7539],
 [4271, 7514, 4508, 2851, 5052, 5938, 4964, 269, 977, 4443, 3120],
 [764, 1545, 5310, 572, 5843, 7426, 5789, 6492, 977, 4443, 3120],
 [3632, 3997, 350, 1449, 7689, 1747, 1008, 7918, 5789, 6484],
 [588, 4233, 1049, 7740, 1138, 7222, 4782, 7311],
 [692, 231, 4063, 3858, 5327, 118, 6262, 6579, 2201, 7603, 4439],
 [7476, 4818, 305, 1747, 5789, 5843],
 [226, 6011, 2768, 2801, 4298, 974, 1133, 6284, 1732],
 [4296, 3504, 600, 2366, 5096, 7224, 990, 977, 4443, 3120],
 [4053, 250, 5303, 6679, 4718, 977, 4443, 3120],
 [1305, 5263, 3932, 4005, 3718, 6963, 6992, 955, 4163, 6090],
 [2522, 7392, 4521],
 [4450, 5142, 2531, 1960, 5789, 2799, 2173, 7539],


In [20]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [21]:
sent_length=20  #max length of sentence
embedded=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded)


[[   0    0    0 ... 5434 6022 6199]
 [   0    0    0 ... 4081 1247 7539]
 [   0    0    0 ... 1146 1530 2676]
 ...
 [   0    0    0 ...  977 4443 3120]
 [   0    0    0 ...  974 7570 3102]
 [   0    0    0 ... 6254 6843 6252]]


In [22]:
embedded[0]#message/sentence is converted to numbers with max 17 numbers /words are numerically represented and zero is padded if less than sent_length

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1523,
       3797, 5091, 2712,  305, 3814, 5437, 5434, 6022, 6199])

In [41]:
from tensorflow.keras.layers import Dropout
features=40 #vector of features
model=Sequential()
model.add(Embedding(voc_size,features,input_length=sent_length))#1st layer
model.add(Dropout(0.3))
model.add(LSTM(100))# LSTM layer with 100 nuerons
model.add(Dropout(0.3))
model.add(Dense(1,activation="sigmoid")) #dense layer for output
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=["accuracy"])

In [42]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            320000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 376,501
Trainable params: 376,501
Non-trainable params: 0
_________________________________________________________________


In [43]:
import numpy as np
X_final=np.array(embedded)
y_final=np.array(y)

In [44]:
X_final.shape

(18285, 20)

In [45]:
X_final

array([[   0,    0,    0, ..., 5434, 6022, 6199],
       [   0,    0,    0, ..., 4081, 1247, 7539],
       [   0,    0,    0, ..., 1146, 1530, 2676],
       ...,
       [   0,    0,    0, ...,  977, 4443, 3120],
       [   0,    0,    0, ...,  974, 7570, 3102],
       [   0,    0,    0, ..., 6254, 6843, 6252]])

In [46]:
y_final.shape

(18285,)

In [47]:
len(embedded),y.shape

(18285, (18285,))

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25
                                                   )

In [49]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
215/215 [==============================] - 9s 44ms/step - loss: 0.3319 - accuracy: 0.8462 - val_loss: 0.2039 - val_accuracy: 0.9180
Epoch 2/10
215/215 [==============================] - 9s 43ms/step - loss: 0.1403 - accuracy: 0.9444 - val_loss: 0.1830 - val_accuracy: 0.9232
Epoch 3/10
215/215 [==============================] - 11s 50ms/step - loss: 0.1010 - accuracy: 0.9641 - val_loss: 0.2028 - val_accuracy: 0.9204
Epoch 4/10
215/215 [==============================] - 11s 52ms/step - loss: 0.0766 - accuracy: 0.9747 - val_loss: 0.2561 - val_accuracy: 0.9206
Epoch 5/10
215/215 [==============================] - 14s 64ms/step - loss: 0.0598 - accuracy: 0.9810 - val_loss: 0.2461 - val_accuracy: 0.9191
Epoch 6/10
215/215 [==============================] - 12s 57ms/step - loss: 0.0431 - accuracy: 0.9857 - val_loss: 0.2850 - val_accuracy: 0.9151
Epoch 7/10
215/215 [==============================] - 11s 49ms/step - loss: 0.0318 - accuracy: 0.9902 - val_loss: 0.2968 - val_accuracy: 0

In [50]:
y_pred=model.predict_classes(X_test)

In [51]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[2404,  212],
       [ 182, 1774]], dtype=int64)

In [53]:
accuracy_score(y_test,y_pred)

0.9138232720909887